/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.productiveAnalytics.aws.dynamodb;

public class MyApplication {
    public String getGreeting() {
        return "Hello DynamoDB.";
    }

    public static void main(String[] args) {
        System.out.println(new MyApplication().getGreeting());
    }
}
